export const ERROR_CODES = {
    // AUTH
    INVALID_CREDENTIALS: 'AUTH_001',
    TOKEN_REQUIRED: 'AUTH_002',
    UNAUTHORIZED: 'AUTH_003',
    FORBIDDEN: 'AUTH_004',

    // USER
    USER_NOT_FOUND: 'USER_001',
    USER_ALREADY_EXISTS: 'USER_002',

    // ROLE
    ROLE_NOT_FOUND: 'ROLE_001',

    // PERMISSION
    PERMISSION_NOT_FOUND: 'PERM_001',

    // SYSTEM
    INTERNAL_ERROR: 'SYS_001',
    NOT_FOUND: 'SYS_002',
    ALREADY_EXIST: 'SYS_003',
    INVALID_FORMAT: 'SYS_004',
    NOT_IMPLEMENTED: 'SYS_005'
}